name = "GLOQ"
uuid = "0340fad7-3f26-4a49-81c0-3451e5087303"
authors = ["Daniel Appelo <appeloda@msu.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
