name = "GLOQ"
uuid = "0340fad7-3f26-4a49-81c0-3451e5087303"
authors = ["Daniel Appelo <appeloda@msu.edu> and contributors"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
Documenter = "0.27"
DocumenterTools = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
